# Generated by Django 3.1.7 on 2022-01-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20220103_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
