# Generated by Django 3.1.7 on 2022-01-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220103_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='items',
            field=models.ManyToManyField(blank=True, to='course.Item'),
        ),
    ]
