# Generated by Django 3.1.7 on 2022-03-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20220131_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ImageField(blank=True, upload_to='tasks_icons'),
        ),
    ]
