# Generated by Django 3.1.7 on 2022-03-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20220323_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='overview',
            field=models.TextField(),
        ),
    ]
