# Generated by Django 3.1.7 on 2022-04-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20220323_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDoHaveTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_have_test', models.PositiveIntegerField(choices=[(1, 'не тестовое'), (2, 'закрытое'), (3, 'открытое')])),
            ],
        ),
        migrations.CreateModel(
            name='TaskMethodOfLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_of_learning', models.PositiveIntegerField(choices=[(1, 'активный'), (2, 'пассивный'), (3, 'интерактивный')])),
            ],
        ),
        migrations.CreateModel(
            name='TaskRSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsp', models.PositiveIntegerField(choices=[(1, 'визуальная'), (2, 'дигитальная'), (3, 'аудиальная')])),
            ],
        ),
        migrations.CreateModel(
            name='TaskTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.PositiveIntegerField(choices=[(1, 'информационная'), (2, 'диагностическая'), (3, 'обучающая'), (4, 'мотивационная')])),
            ],
        ),
        migrations.CreateModel(
            name='TaskTargetAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_audience', models.PositiveIntegerField(choices=[(1, 'дети'), (2, 'взрослые')])),
            ],
        ),
        migrations.CreateModel(
            name='TaskTestProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_property', models.PositiveIntegerField(choices=[(1, 'динамическое'), (2, 'стохастическое'), (3, 'детерминированное')])),
            ],
        ),
        migrations.CreateModel(
            name='TaskToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_token', models.PositiveIntegerField(choices=[(1, 'слово'), (2, 'словосочетание'), (3, 'предложение'), (4, 'абзац'), (5, 'текст')])),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='adaptivity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='chalenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='effectivity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='fast_to_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='fast_to_do',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='gaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='toAA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='toBOFI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='toLM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='toQER',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='toVM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='toVMWP',
            field=models.BooleanField(default=False),
        ),
    ]
