# Generated by Django 3.1.7 on 2022-04-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20220410_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isOnSite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='have_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='course.taskdohavetest'),
        ),
        migrations.AlterField(
            model_name='task',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='course.taskmethodoflearning'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rsp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='course.taskrsp'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='course.tasktarget'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='course.tasktargetaudience'),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='course.tasktestproperties'),
        ),
        migrations.AlterField(
            model_name='task',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='course.tasktheme'),
        ),
        migrations.AlterField(
            model_name='task',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='course.tasktoken'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='course.tasktype'),
        ),
    ]
