# Generated by Django 3.1.7 on 2022-01-03 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bofi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BOFI', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Memory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QER', to=settings.AUTH_USER_MODEL),
        ),
    ]
