# Generated by Django 3.1.7 on 2022-03-08 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20220117_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='LM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveIntegerField(validators=[user_profile.validators.memory_validator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_init'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveIntegerField(validators=[user_profile.validators.memory_validator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VM', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_init'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VMWP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveIntegerField(validators=[user_profile.validators.memory_validator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VMWP', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_init'],
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='aa',
            old_name='AA',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='bofi',
            old_name='BOFI',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='qer',
            old_name='QER',
            new_name='value',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
