# Generated by Django 3.1.7 on 2022-03-19 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20220308_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LM', to=settings.AUTH_USER_MODEL),
        ),
    ]
