# Generated by Django 3.1.7 on 2022-03-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20220319_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, upload_to='static\\profile_icons'),
        ),
    ]
