# Generated by Django 3.1.7 on 2022-01-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertasks',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usertasks',
            name='user',
        ),
        migrations.AddField(
            model_name='usertasks',
            name='usercourse',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='user_activities.usercourses'),
            preserve_default=False,
        ),
    ]
