# Generated by Django 3.1.7 on 2022-01-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0002_auto_20220126_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertasks',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
