# Generated by Django 3.1.7 on 2022-01-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0005_auto_20220131_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourses',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
