# Generated by Django 3.1.7 on 2022-03-21 07:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_activities', '0007_userdaily'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdaily',
            unique_together={('user', 'date_init')},
        ),
    ]
